### PR TITLE
Adding l10n support for German

### PR DESCRIPTION
**Pull request by tijuca**
Hi,

I added a German translation to TbSync. Feel free to request some needed modifications if I messed something.

### CODE REVIEW

**Comment by jobisoft** [comment]
Thanks. Can you revert all changes to install.rdf and just add

```
        <em:localized>
          <Description>
            <em:locale>de</em:locale>
            <em:description>Synchronisiert Exchange ActiveSync Konten (Kontakte, Aufgaben und Kalender) mit Thunderbird</em:description>
          </Description>
        </em:localized>
```

between line 25 and 26 at the end?

```
23           </Description>
24
25        </em:targetApplication>
26    </Description>
27</RDF>
```

You introduced the RDF namespace which I do not see necesarry and you used the wrong AddOn name (CompactHeader instead of TbSync) :-).

**Comment by tijuca** [comment]
Hrhr, yes. Will do. Stupid copy paste error. ;)

**Comment by jobisoft** [comment]
If you have problems reverting, simply take the original version from here:
https://github.com/jobisoft/TbSync/blob/master/install.rdf

and save it over your version and commit.

**Comment by tijuca** [comment]
Thanks, but the source for the branch this PR was made of is simply on an other machine. Anyway, I modified the branch to fulfil your request and pushed all again.

I added a small technically non modifying commit in the middle so the last commit for adding some German strings to install.rdf is more clearly and encapsulated. I hope it's fine now. A test right now was successful.

**Comment by jobisoft** [comment]
Thanks!

**Comment by jobisoft** [comment]
Could you take a look at
https://github.com/jobisoft/TbSync/commit/abae4ea48afebcac7697c0f0a01769f0c509b463

Your fork was outdated and did not include all locale fields. I added them to the de locale files (in english), could you translate them as well and do a new PR. I usually throw away my forks an re-fork, instead to get my fork updated.

Thanks for your contribution.

**Comment by tijuca** [comment]
Sure, will do this later this week.

The work was based on 0.7.7(.0) so yes, it's obviously a bit outdated to the recent state.

**Pull request merged**
