### PR TITLE
TbSync hu (magyar - Hungarian) translation

### PR DESCRIPTION
**Pull request by ovari**
https://github.com/jobisoft/TbSync/issues/150

### CODE REVIEW

**Comment by jobisoft** [comment]
Thanks for your contribution. After merging, I will probably remove the redundant em:translator tags and only keep the one at the top. Would that be ok?

**Comment by ovari** [comment]
With Thunderbird 52, if the em:translator tags were not in the localized section the names didn't show up. Has this been fixed with Thunderbird 60? If so then they are redundant and please remove. Thank you

**Comment by jobisoft** [comment]
I will check and I did not know that. Thanks again!

**Comment by jobisoft** [comment]
Can you tell me, where the names should show up? I do not see them at all... Screenshoot?

**Comment by ovari** [comment]
1. Add-ons Manager
2. Extensions
3. Right-click on add-on
4. About

Please see screenshots above.

**Comment by jobisoft** [comment]
Ah, in the about window, never opened that before. I would then go for having translators tag only inside the localized tag and just the one belonging to that translation. That removes all redundancy as well. You with me?

**Comment by jobisoft** [comment]
Alright, merging as is.

**Comment by ovari** [comment]
Thank you!

**Pull request merged**
