### PR TITLE
Image for Wiki help page

### PR DESCRIPTION
**Pull request by ldmpub**
How to enable debug logging

### CODE REVIEW

**Comment by ldmpub** [comment]
Don't hesitate to revert if this is not the good way to work together.

**Comment by jobisoft** [comment]
That is fine. However, I am about to change licence from gpl2 to gpl3+. Since you contributed under the old licence, i need your consent to update the licence.

Also, please point out in your wiki post, that user should ALWAYS update to the latest beta version, to check if their bug has been fixed already, before sending in a report. That information is present just above the checkbox you pointed out in your image.

Thanks for your help!

**Comment by ldmpub** [comment]
- On your request, to indicate "user should ALWAYS update" => words are in bold at the top of the wiki page (you can improve this part)
- Images committed directly to master/screenshot/...
- Sorry my first image filename contains "space characters" => you can rename it if needed.

Tell me if it's ok for you.

**Comment by jobisoft** [comment]
It is probably better, if you remove the spaces from the filename.

Thanks for your help!

I still need your written consent to change the licence to "gpl 3 or newer".

**Comment by ldmpub** [comment]
File name change (without space) + Licence consent send by mail.

**Comment by jobisoft** [comment]
Thanks!

**Pull request closed without merging**
