### PR TITLE
Add translations installl.rdf and chrome.manifest

### PR DESCRIPTION
**Pull request by wanderleihuttel**

### CODE REVIEW

**Comment by jobisoft** [comment]
I released new betas, your Translation should now show up. Send in a new PR, if you want to update your translation.

To get the new beta, simply select "Update AddOns" from the gear-menu in the Thunderbird AddOnManager.

**Comment by jobisoft** [comment]
The menu entry is called "Check for updates", it is the first one. Sorry

**Comment by wanderleihuttel** [comment]
Hello @jobisoft !
After install I'm receiving the error below when I've try to enter in the TBSync Add-On Option:

XML Parsing Error: error in processing external entity reference
Location: chrome://tbsync/content/manager/addonoptions.xul
Line Number 3, Column 60:<!DOCTYPE window SYSTEM "chrome://tbsync/locale/tbSync.dtd">
-----------------------------------------------------------^

**Comment by jobisoft** [comment]
What version of TB are you using ? TbSync only works with TB60.

**Comment by jobisoft** [comment]
Oh, at

Line Number 3, Column 60

I load tbSync.dtd, Looks like sometuing is wrong with your locale file. I investigate.

**Comment by wanderleihuttel** [comment]
I've made a test and downloaded a fresh install of thunderbird and installed the 3 extensions manually and the same errors occurred, even restarting the Thunderbird

**Comment by jobisoft** [comment]
Done. Please update addons and try again (you may not use " inside an Entity, you did that in manager.catman.text)


Can you check your other translations for " usage inside translations? Yopu can use ' or any other UTF-8 Quote sign, but not the standard "

**Comment by wanderleihuttel** [comment]
Now after update it worked! I guess is the only place that I've used the double quotes,
I will review the translations to see if everything is fine.

Thanks

**Comment by wanderleihuttel** [comment]
I've finished a tweak modification in translations, and now all 3 add-ons worked OK.
If you want release a new beta I can install and check again.

**Comment by wanderleihuttel** [comment]
I only removed the quotes from that words, because I thought is not necessary in portuguese translation.
I don't know any other kind of quotation using the keyboard ABNT2. I know thats is possible to copy and paste some quotation characters from somewhere, but I guess this is not productive.
I'm using notepad++ for translate.

**Comment by jobisoft** [comment]
I changed the quotes to « and » and released new betas for you to test.

**Comment by jobisoft** [comment]
I would not translate Category Manager, since it is a name. How do you refer to „Microsoft Office“, do you use the native translation for that, or the English original? For Category Manager I would behave the same, I think.

I think it is ok to stick with ActiveSync Version and ActiveSync device Id. If you evervwant to change that, create a PR :-)

I will do the other change but probably do not release a beta just for that.

**Comment by wanderleihuttel** [comment]
About "Category Manager", no problem because in the description is explaining what is "Category Manager"
About ActiveSync, no problem, but there is a string in the file eas.dtd:
pref.ActiveSyncVersion and pref.DeviceId.

And thanks for the change.

Do have an estimation to release an oficial version with the pt-BR translations?
And if you have more strings to translate, not hesitate to ask me.

Thanks again

**Comment by jobisoft** [comment]
I still want to fix this bug:
https://github.com/jobisoft/EAS-4-TbSync/issues/49

And the new mailinglist sync of TB Needs some beta Tests before release. I hope to release it this month.

**Pull request merged**
