### PR TITLE
Recurring Events

### PR DESCRIPTION
**Pull request by ChrisJAllan**
I was unable to push recurrences on multiple days of the month. The documentation seems to suggest that multiple Recurrence tags could work as long as they don't overlap, but when I tried that the sync failed with an invalid item. [(Request XML)](https://github.com/jobisoft/TbSync/files/1608250/MultipleRecurrence.txt) I also couldn't create such an event from the online Outlook, so I'm unsure if it supports them at all. Maybe the desktop app is different, but I don't have access to that.

I also left out support for non-default calendar types because it seemed like far too much of a hassle for the benefit. IsLeapMonth is also not needed or useful with the Gregorian calendar and has been left out.

Edit: Noticed that pulling nth-week events don't work.
Edit: Fixed

### CODE REVIEW

**Comment by ChrisJAllan** [comment]
Noticed that pulling week-based events don't work.

**Comment by ChrisJAllan** [comment]
Fixed

**Comment by jobisoft** [comment]
Thanks for your great work! I pull this directly and test it against other EAS providers in the next week!

Do you want to be listed in a new contributer section in the TbSync help screen? With what information?

**Comment by ChrisJAllan** [comment]
I just realized my last commit didn't change line 657. Probably won't break anything, but should be `let weeks = []`. 

I don't think it's necessary to change the help screen for me.

**Comment by jobisoft** [comment]
so i have to change
                let weeks     = recRule.getComponent("BYWEEKNO", {});
to
                let weeks = [] 
?

**Comment by jobisoft** [comment]
Horde: works!

**Comment by jobisoft** [comment]
zpush: works!
Microsft EAS: works!

So it works with all major EAS server implementations I know of. Nice!

**Pull request merged**
