### PR TITLE
Prevent writing of config files before properties are initialised

### PR DESCRIPTION
**Pull request by Dagefoerde**
This is an initial attempt at fixing issue #133, but it is untested. Do not merge (yet)!

### CODE REVIEW

**Comment by jobisoft** [comment]
is the observer called upon app close?

**Comment by Dagefoerde** [comment]
No, but the shutdown hook is already checking for `tbSync.enabled`, so that idea of mine can't be the root of the problem either.
https://github.com/jobisoft/TbSync/blob/2cd2711287d050e047ac876dad57f8c979cc4800/bootstrap.js#L115

However, if other events trigger the observer before the configuration is initialised this would prevent it from saving to the files.

**Comment by jobisoft** [comment]
ok, I was hoping, that I was missing that check to have an Explanation for your issue.
Adding the check for the other writes is of course needed as well.

To fix the "I did not know my account data was gone" I could add starup check, if accounts are defined and if not, pop a prompt to open the Manager to add an account. This would also help and guide new users. Would that be sufficient?

**Comment by Dagefoerde** [comment]
Oh yes, that would be a very good idea! I do recall not knowing where I could configure my exchange account when I started using the plugin.

**Comment by jobisoft** [comment]
I think this is an important step: We/You need to find a way to reproduce the issue with the current code, so we can check if the fix is realy fixing it. That might be harder than it sounds …

**Comment by jobisoft** [comment]
I will release a new version shortly, can I merge this as I think it it needed?

**Comment by jobisoft** [comment]
Thanks for your work! I appreciate any support I can get :-) 

If you like to further work on this subject, than you could try to find out how to reproduce that corruption error (without your fix) so we can see if your fix is enough to prevent it or if we have to think about backups.

You could also think about that backup strategy.

Thanks again for your support.

**Pull request merged**
