### PR TITLE
Overwrite Displayname use also Company and Emailaddress

### PR DESCRIPTION
**Pull request by puran2**
If you use the option "overwrite displayname" the company resp. the emailaddress will be use if the name is empty.

### CODE REVIEW

**Comment by jobisoft** [comment]
thanks!

what is this needed for?
https://github.com/jobisoft/TbSync/pull/19/files#diff-2c71a8c4ad50247f7f8db81795ffcbd4R19

**Comment by puran2** [comment]
I sort my addressbook with the display name and I have many company's in it without a contact so the displayname is not empty

**Comment by jobisoft** [comment]
Sorry, the link in my post points to a specific line of your commit, where you introduce console.jsm.

I asked: What is that needed for?
I did understand, what your commit is about :-)

**Comment by jobisoft** [comment]
please remove insatll.rdf from your PR

**Comment by puran2** [comment]
I have to see how it works

**Comment by jobisoft** [comment]
simple change the version number back (remove -19) and commit in your repository, it will be merged into your PR and since there are no more changes, it will drop out of your PR and the conflict is resolved.

**Comment by jobisoft** [comment]
if that does not work, change it to the current version number (0.6.8.2)

**Comment by puran2** [comment]
The version number is no 0.6.8.2

**Comment by puran2** [comment]
thank you

**Comment by jobisoft** [comment]
You have contributed to TbSync:

I am asking for your consent to upgrade the license of TbSync to "GPL 3.0 or later". 
Also I would like to ask for your consent to include the "Fiduciary Licence Agreement (FLA)".

**Comment by puran2** [comment]
It’s ok. What should I do ?

**Comment by jobisoft** [comment]
Thats all, thank you.

**Pull request merged**
