### PR TITLE
Minor English language improvements

### PR DESCRIPTION
**Pull request by DzamoNorton**

### CODE REVIEW

**Comment by jobisoft** [comment]
Thanks again! Would you also like to check wiki?

**Comment by DzamoNorton** [comment]
Yes.  I have been able to clone the wiki git repo.  What happens after I've made changes?  Will I be able to push them back to Github?

**Comment by jobisoft** [comment]
Lets try! I first have to enable you as collaborator (you will get an email), after that, it should work.

**Comment by jobisoft** [comment]
If not, you have to edit the wiki itself (via web gui of github). I just send out the invite.

**Comment by DzamoNorton** [comment]
Thanks @jobisoft, I have access now and will do some editing from time to time.

**Comment by jobisoft** [comment]
You have contributed to TbSync:

I am asking for your consent to upgrade the license of TbSync to "GPL 3.0 or later".
Also I would like to ask for your consent to include the "Fiduciary Licence Agreement (FLA)".

**Pull request merged**
